import { expect, test } from '@playwright/test'
import { activateEditor, documentJSON, openEditor, selectText, stored } from './editor/editor-helpers'

const outerTab = (page: import('@playwright/test').Page, name: string) => page.getByRole('tablist', { name: 'UI explorations' }).getByRole('tab', { name, exact: true })
test.beforeEach(async ({ page }) => { await page.setViewportSize({ width: 1640, height: 1060 }) })

test('Header remains initial; five lazy tabs keep switcher semantics, indicator and keyboard focus', async ({ page }) => {
  const editorRequests: string[] = []
  page.on('request', request => { if (request.url().includes('/src/document-editor/')) editorRequests.push(request.url()) })
  await page.goto('/')
  await expect(outerTab(page, 'Header')).toHaveAttribute('aria-selected', 'true')
  await expect(page.getByRole('tablist', { name: 'UI explorations' }).getByRole('tab')).toHaveText(['Header', 'Date picker', 'Profile', 'Document editor', 'Facility app'])
  await expect(page.getByTestId('document-editor')).toHaveCount(0)
  expect(editorRequests).toEqual([])
  await outerTab(page, 'Header').focus()
  for (const name of ['Date picker', 'Profile', 'Document editor']) {
    await page.keyboard.press('ArrowRight')
    await expect(outerTab(page, name)).toBeFocused()
    await expect(outerTab(page, name)).toHaveAttribute('aria-selected', 'true')
    const id = await outerTab(page, name).getAttribute('aria-controls')
    await expect(page.locator(`#${id}`)).toBeVisible()
  }
  await expect(page.getByTestId('document-editor')).toBeVisible()
  expect(editorRequests.length).toBeGreaterThan(0)
  await expect(outerTab(page, 'Document editor')).toBeFocused()
  await page.keyboard.press('Home'); await expect(outerTab(page, 'Header')).toBeFocused()
  await page.keyboard.press('End'); await expect(outerTab(page, 'Facility app')).toBeFocused()
  await expect(async () => {
    const tab = (await outerTab(page, 'Facility app').boundingBox())!, indicator = (await page.locator('.exploration-switcher__indicator').boundingBox())!
    expect(Math.abs(tab.x - indicator.x)).toBeLessThanOrEqual(1)
    expect(Math.abs(tab.width - indicator.width)).toBeLessThanOrEqual(1)
  }).toPass()
  await page.keyboard.press('ArrowRight'); await expect(outerTab(page, 'Header')).toBeFocused()
})

test('editor stays mounted with mapped selection, workspace scroll, comments and panel drafts; hidden autosave and refresh persist', async ({ page }) => {
  await openEditor(page, 200)
  const node = await page.getByTestId('document-editor').elementHandle()
  await selectText(page, 'Dear Alex,'); await page.keyboard.type('Integration retained')
  await selectText(page, 'Acme Studio')
  await page.getByRole('tab', { name: 'Comments', exact: true }).click()
  await page.getByLabel('New comment').fill('Posted integration comment')
  await page.getByRole('button', { name: 'Comment on selection', exact: true }).click()
  await page.getByLabel('New comment').fill('Unsubmitted comment draft')
  await page.getByLabel('Reply', { exact: true }).fill('Unsubmitted reply draft')
  await page.getByTestId('workspace').evaluate(el => { el.scrollTop = 240 })
  const before = await documentJSON(page)
  const selection = await page.evaluate(() => { const s = window.__phase2Test!.editor!.state.selection; return { from: s.from, to: s.to } })
  const scroll = await page.getByTestId('workspace').evaluate(el => el.scrollTop)
  await outerTab(page, 'Profile').click()
  await expect(page.getByTestId('document-editor')).toBeHidden()
  await expect.poll(async () => JSON.stringify((await stored(page))?.document)).toBe(JSON.stringify(before))
  await outerTab(page, 'Date picker').click(); await outerTab(page, 'Header').click(); await activateEditor(page)
  expect(await node!.evaluate(el => el === document.querySelector('[data-testid="document-editor"]'))).toBe(true)
  expect(await documentJSON(page)).toEqual(before)
  expect(await page.evaluate(() => { const s = window.__phase2Test!.editor!.state.selection; return { from: s.from, to: s.to } })).toEqual(selection)
  expect(await page.getByTestId('workspace').evaluate(el => el.scrollTop)).toBe(scroll)
  await expect(page.getByLabel('New comment')).toHaveValue('Unsubmitted comment draft')
  await expect(page.getByLabel('Reply', { exact: true })).toHaveValue('Unsubmitted reply draft')
  await page.reload()
  await expect(outerTab(page, 'Header')).toHaveAttribute('aria-selected', 'true')
  await expect(page.getByTestId('document-editor')).toHaveCount(0)
  await activateEditor(page)
  await expect(page.getByTestId('document-editor')).toContainText('Integration retained')
  await page.getByRole('tab', { name: 'Comments', exact: true }).click()
  await expect(page.getByText('Posted integration comment', { exact: true })).toBeVisible()
})

test('hidden editor releases shortcuts, removes floating surfaces and cancels pending Explain without stealing tab focus', async ({ page }) => {
  await openEditor(page)
  await selectText(page, 'Acme Studio')
  await page.getByRole('button', { name: 'Ask AI', exact: true }).click()
  await page.getByTestId('explain-menu').getByRole('button', { name: /^Summary/ }).click()
  await expect(page.getByText('Generating response…', { exact: true })).toBeVisible()
  await outerTab(page, 'Header').click()
  await expect(outerTab(page, 'Header')).toBeFocused()
  await expect(page.getByTestId('explain-menu')).toHaveCount(0)
  await expect(page.getByTestId('formatting-toolbar')).toHaveCount(0)
  const before = await documentJSON(page)
  const cancelled = await page.evaluate(() => ['f', 's', 'F10', 'Tab', 'Escape'].map(key => {
    const event = new KeyboardEvent('keydown', { key, ctrlKey: key.length === 1, bubbles: true, cancelable: true })
    document.dispatchEvent(event)
    return event.defaultPrevented
  }))
  expect(cancelled).toEqual([false, false, false, false, false])
  await expect(outerTab(page, 'Header')).toBeFocused()
  await page.waitForTimeout(700)
  await page.keyboard.press('End'); await page.keyboard.press('ArrowLeft')
  await expect(outerTab(page, 'Document editor')).toBeFocused()
  await expect(page.getByText('Response cancelled.', { exact: true })).toBeVisible()
  await expect(page.getByTestId('explain-result')).toHaveCount(0)
  expect(await documentJSON(page)).toEqual(before)
  await page.getByRole('button', { name: 'Retry', exact: true }).click()
  await expect(page.getByTestId('explain-result')).toBeVisible()
  const result = await page.getByTestId('explain-result').innerText()
  await outerTab(page, 'Header').click(); await page.keyboard.press('End'); await page.keyboard.press('ArrowLeft')
  await expect(outerTab(page, 'Document editor')).toBeFocused()
  await expect(page.getByTestId('explain-result')).toHaveText(result)
  await page.getByTestId('explain-menu').press('Escape')
  await selectText(page, 'Dear Alex,')
  await page.getByRole('button', { name: 'Text color', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'Text color choices' })).toBeVisible()
  await outerTab(page, 'Profile').click()
  await expect(outerTab(page, 'Profile')).toBeFocused()
  await expect(page.getByRole('dialog', { name: 'Text color choices' })).toHaveCount(0)
  await activateEditor(page)
  await page.keyboard.press('Control+f')
  await expect(page.getByRole('textbox', { name: 'Search document', exact: true })).toBeFocused()
  await selectText(page, 'Bloom')
  await page.getByRole('button', { name: 'Ask AI', exact: true }).click()
  await page.getByTestId('explain-menu').getByRole('button', { name: /^Ask a question/ }).click()
  await page.getByLabel('Ask anything about this text').fill('Retained question draft')
  await outerTab(page, 'Header').click(); await page.keyboard.press('End'); await page.keyboard.press('ArrowLeft')
  await expect(outerTab(page, 'Document editor')).toBeFocused()
  await expect(page.getByLabel('Ask anything about this text')).toHaveValue('Retained question draft')
})

test('existing Header, Date picker and Profile interactions still work after editor activation', async ({ page }) => {
  await openEditor(page)
  await outerTab(page, 'Header').click()
  const products = page.getByRole('button', { name: 'Products', exact: true })
  await products.focus(); await page.keyboard.press('ArrowDown')
  await expect(products).toHaveAttribute('aria-expanded', 'true')
  await page.keyboard.press('Escape')
  await expect(products).toBeFocused()
  await expect(products).toHaveAttribute('aria-expanded', 'false')
  await outerTab(page, 'Date picker').click()
  const datePanel = page.locator('#exploration-panel-date-picker')
  await expect(datePanel.getByRole('button').first()).toBeVisible()
  await datePanel.getByRole('button', { name: 'Today', exact: true }).click()
  await expect(datePanel.getByRole('button', { name: 'Today', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await outerTab(page, 'Profile').click()
  await expect(page.locator('#exploration-panel-profile')).toBeVisible()
  await expect(page.locator('#exploration-panel-profile').getByRole('button').first()).toBeEnabled()
})
