import { chromium, expect } from '@playwright/test'
import fs from 'node:fs'
export async function productionSmoke(url, { local = false } = {}) {
  const browser = await chromium.launch()
  const page = await browser.newPage({ viewport: { width: 1640, height: 1060 }, reducedMotion: 'reduce' })
  const errors = [], failed = [], requests = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('response', response => { if (response.status() >= 400) failed.push(`${response.status()} ${response.url()}`) })
  page.on('request', request => requests.push(request.url()))
  try {
    await page.addInitScript(() => { window.__phase2Test = { saveDelay: 120000, explainFailures: 99 } })
    await page.goto(url)
    await expect(page.getByRole('tab', { name: 'Header', exact: true })).toHaveAttribute('aria-selected', 'true')
    await expect(page.getByTestId('document-editor')).toHaveCount(0)
    expect(requests.some(url => /(?:DocumentEditorDemo|FacilityAppDemo).*\.js/.test(url))).toBe(false)
    await expect(page.getByRole('tablist', { name: 'UI explorations' }).getByRole('tab')).toHaveText(['Header', 'Date picker', 'Profile', 'Document editor', 'Facility app'])
    await page.getByRole('tab', { name: 'Header', exact: true }).focus()
    for (const name of ['Date picker', 'Profile', 'Document editor']) {
      await page.keyboard.press('ArrowRight')
      await expect(page.getByRole('tab', { name, exact: true })).toBeFocused()
    }
    await page.keyboard.press('ArrowRight')
    await expect(page.getByRole('tab', { name: 'Facility app', exact: true })).toBeFocused()
    await expect(page.locator('.facility-app-scope')).toBeVisible()
    await page.evaluate(() => document.fonts.ready)
    expect(await page.locator('.facility-app-scope img').evaluateAll(images => images.every(img => img.complete && img.naturalWidth > 0))).toBe(true)
    expect(await page.evaluate(() => [...document.fonts].some(f => f.family === 'Facility Inter' && f.status === 'loaded'))).toBe(true)
    await expect(page.locator('.facility-app-scope .runtime-row.is-selected')).toHaveAttribute('data-equipment', 'AHU-03')
    await page.screenshot({ path: `docs/qa/facility-app/${local ? 'production-local' : 'deployed'}-verified.png` })
    await page.getByRole('tab', { name: 'Document editor', exact: true }).click()
    const editor = page.getByTestId('document-editor')
    await expect(editor).toBeVisible()
    await expect(page.getByTestId('save-status')).toHaveText('Saved')
    expect(await page.evaluate(() => !!window.__phase2Test.editor)).toBe(false)
    await editor.click()
    await page.keyboard.press('ControlOrMeta+Home')
    await page.keyboard.type('Deployment verification ')
    await page.getByRole('button', { name: 'Save changes', exact: true }).click()
    await expect(page.getByTestId('save-status')).toHaveText('Saved')
    await page.getByRole('tab', { name: 'Comments', exact: true }).click()
    await page.getByLabel('New comment').fill('Production integration check')
    await page.getByRole('button', { name: 'Add document comment', exact: true }).click()
    await page.getByLabel('New comment').fill('Retained draft')
    await page.getByTestId('workspace').evaluate(el => { el.scrollTop = 210 })
    const scroll = await page.getByTestId('workspace').evaluate(el => el.scrollTop)
    await page.getByRole('tab', { name: 'Header', exact: true }).click()
    const prevented = await page.evaluate(() => ['f', 's'].map(key => { const e = new KeyboardEvent('keydown', { key, ctrlKey: true, bubbles: true, cancelable: true }); document.dispatchEvent(e); return e.defaultPrevented }))
    expect(prevented).toEqual([false, false])
    await page.getByRole('tab', { name: 'Document editor', exact: true }).click()
    await expect(page.getByLabel('New comment')).toHaveValue('Retained draft')
    expect(await page.getByTestId('workspace').evaluate(el => el.scrollTop)).toBe(scroll)
    await page.getByRole('button', { name: 'Save changes', exact: true }).click()
    await expect(page.getByTestId('save-status')).toHaveText('Saved')
    await page.reload()
    await expect(page.getByRole('tab', { name: 'Header', exact: true })).toHaveAttribute('aria-selected', 'true')
    await page.getByRole('tab', { name: 'Document editor', exact: true }).click()
    await expect(editor).toContainText('Deployment verification')
    await page.getByRole('tab', { name: 'Comments', exact: true }).click()
    await expect(page.getByText('Production integration check', { exact: true })).toBeVisible()
    await page.getByRole('tab', { name: 'History', exact: true }).click()
    await expect(page.locator('[data-revision-id]').first()).toBeVisible()
    await page.getByRole('button', { name: 'Explain mode', exact: true }).click()
    await page.locator('[data-clause-marker]').first().click()
    await page.getByTestId('explain-menu').getByRole('button', { name: /^Summary/ }).click()
    await expect(page.getByTestId('explain-result')).toBeVisible()
    await page.evaluate(() => document.fonts.ready)
    const assets = await page.locator('.document-editor-scope img').evaluateAll(images => images.every(img => img.complete && img.naturalWidth > 0))
    expect(assets).toBe(true)
    expect(await page.evaluate(() => document.fonts.check('14px "Proposal Inter"'))).toBe(true)
    await page.screenshot({ path: `docs/qa/document-editor/${local ? 'production-local' : 'deployed'}-verified.png` })
    if (local) for (const route of ['/fixtures/default', '/fixtures/selection-explain']) {
      await page.goto(`${url}${route}`)
      await expect(page.getByRole('tab', { name: 'Header', exact: true })).toHaveAttribute('aria-selected', 'true')
      await page.getByRole('tab', { name: 'Document editor', exact: true }).click()
      await expect(editor).toBeVisible()
      expect(await page.evaluate(() => !!window.__phase2Test.editor)).toBe(false)
      await expect(page.getByTestId('fixture-saving')).toHaveCount(0)
    }
    expect(errors).toEqual([])
    expect(failed).toEqual([])
    const result = { url, checkedAt: new Date().toISOString(), errors, failed, passed: true, checks: ['Header initial', 'five keyboard tabs', 'Phase 1 Facility visible with AHU-03 and local font/assets', 'lazy production chunk', 'native editing', 'save/reload', 'Comments and History', 'draft and scroll retention', 'hidden shortcuts', 'Explain result', 'source assets/font', 'inert test adapter'] }
    fs.writeFileSync(`docs/qa/document-editor/${local ? 'production-local' : 'deployment'}-verification.json`, JSON.stringify(result, null, 2))
    fs.writeFileSync(`docs/qa/facility-app/${local ? 'production-local' : 'deployment'}-verification.json`, JSON.stringify(result, null, 2))
    console.log(JSON.stringify(result, null, 2))
  } finally { await browser.close() }
}
if (process.argv[2]) await productionSmoke(process.argv[2])
