import { test, expect } from '@playwright/test'
import { reloadEditor, openEditor, selectText, stored } from './editor-helpers'

test('core editing, keyboard selection, formatting, undo/redo, save and reload', async ({ page }) => {
  await page.setViewportSize({ width: 1640, height: 1060 })
  await openEditor(page)
  const editor = page.getByTestId('document-editor')
  // Native mouse selection and keyboard editing exercise the browser's contenteditable path.
  await editor.locator('h1').click({ clickCount: 3 })
  await page.keyboard.type('Updated proposal')
  await expect(editor.locator('h1')).toHaveText('Updated proposal')
  await page.keyboard.press('Shift+Home')
  await expect(page.getByTestId('formatting-toolbar')).toBeVisible()
  await page.keyboard.press('Meta+b')
  await page.keyboard.type('New title')
  await expect(editor.locator('h1 strong')).toHaveText('New title')
  await page.keyboard.press('Meta+z')
  await expect(editor.locator('h1')).toHaveText('Updated proposal')
  await page.keyboard.press('Meta+Shift+z')
  await expect(editor.locator('h1')).toHaveText('New title')
  await selectText(page, 'Acme Studio')
  await page.getByRole('button', { name: 'Italic', exact: true }).click()
  await expect(editor.locator('em')).toHaveText('Acme Studio')
  await page.keyboard.press('Meta+s')
  await expect(page.getByTestId('save-status')).toHaveText('Saved')
  expect(JSON.stringify((await stored(page)).document)).toContain('New title')
  await reloadEditor(page)
  await expect(editor.locator('h1')).toHaveText('New title')
  await expect(editor.locator('em')).toHaveText('Acme Studio')
  await page.getByRole('button', { name: '7. Next Step', exact: true }).click()
  await expect(editor.getByRole('heading', { name: 'Next Step' })).toBeInViewport()
  expect(await page.evaluate(() => scrollY)).toBe(0)
})

test('Explain marker, keyboard menu, rewrite Apply and undo across browsers', async ({ page }) => {
  await page.setViewportSize({ width: 1640, height: 1060 })
  await openEditor(page)
  await page.getByRole('button', { name: 'Explain mode', exact: true }).click()
  const marker = page.getByRole('button', { name: 'Explain investment', exact: true })
  await marker.focus()
  await page.keyboard.press('Enter')
  const menu = page.getByRole('dialog', { name: 'Explain this', exact: true })
  await expect(menu.getByRole('button').first()).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(page.getByTestId('explain-result')).toContainText('does not specify an amount')
  await page.keyboard.press('Escape')
  await expect(marker).toBeFocused()
  await selectText(page, 'Acme Studio proposes a comprehensive redesign of the Bloom website to create a more modern, intuitive, and conversion-focused experience. The new site will better communicate your value, support business growth, and be easier for your team to manage.')
  const before = await page.locator('#executive-summary + p').innerText()
  await page.getByRole('button', { name: 'Ask AI', exact: true }).click()
  await menu.getByRole('button', { name: /^Rewrite Make/ }).click()
  await expect(page.getByRole('button', { name: 'Apply', exact: true })).toBeEnabled()
  await page.getByRole('button', { name: 'Apply', exact: true }).click()
  await expect(page.locator('#executive-summary + p')).not.toHaveText(before)
  await page.keyboard.press('Meta+z')
  await expect(page.locator('#executive-summary + p')).toHaveText(before)
})

test('comments, keyboard tabs, revision preview/restore and close/reopen across browsers', async ({ page }) => {
  await page.setViewportSize({ width: 1280, height: 900 })
  await openEditor(page)
  await expect(page.getByTestId('save-status')).toHaveText('Saved')
  await selectText(page, 'Acme Studio')
  await page.getByRole('tab', { name: 'Explain', exact: true }).focus()
  await page.keyboard.press('ArrowRight')
  await page.getByLabel('New comment').fill('Browser smoke comment')
  await page.getByRole('button', { name: 'Comment on selection', exact: true }).click()
  await page.getByRole('button', { name: 'Show quoted text', exact: true }).click()
  await page.keyboard.press('Backspace')
  await expect(page.getByText('Detached — quoted text was removed.', { exact: true })).toBeVisible()
  await page.keyboard.press('Meta+s')
  await expect(page.getByTestId('save-status')).toHaveText('Saved')
  await reloadEditor(page)
  await page.getByRole('tab', { name: 'Comments', exact: true }).click()
  await expect(page.getByText('Browser smoke comment', { exact: true })).toBeVisible()
  await page.getByRole('tab', { name: 'History', exact: true }).click()
  await page.locator('[data-revision-id]').last().click()
  await expect(page.getByRole('region', { name: 'Revision preview' })).toContainText('Acme Studio')
  await page.getByRole('button', { name: 'Restore revision', exact: true }).click()
  await expect(page.getByRole('tab', { name: 'History', exact: true })).toBeFocused()
  await expect(page.getByTestId('document-editor')).toContainText('Acme Studio')
  await page.getByRole('button', { name: 'Close document tools', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Explain mode', exact: true })).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(page.getByTestId('right-panel')).toBeVisible()
  await expect(page.locator('[data-clause-marker]')).toHaveCount(3)
})
