import { test, expect } from '@playwright/test'
import { mkdir, writeFile } from 'node:fs/promises'
import { openEditor, selectText } from './editor-helpers'
const output = 'docs/qa/document-editor/inherited-phase-4'
for (const viewport of [{ width: 1640, height: 1060 }, { width: 1280, height: 900 }, { width: 1440, height: 900 }, { width: 1920, height: 1080 }]) {
  test(`Comments, History, focused controls and internal scrolling at ${viewport.width}`, async ({ page }) => {
    const errors: string[] = []
    page.on('pageerror', error => errors.push(error.message))
    await page.clock.install({ time: new Date('2026-10-08T08:00:00.000Z') })
    await page.setViewportSize(viewport)
    await openEditor(page)
    await expect(page.getByTestId('save-status')).toHaveText('Saved')
    await selectText(page, 'Acme Studio')
    await page.getByRole('button', { name: 'Bold', exact: true }).click()
    await page.mouse.move(4, 4)
    await mkdir(output, { recursive: true })
    await page.screenshot({ path: `${output}/formatting-active-${viewport.width}.png` })
    await page.getByRole('tab', { name: 'Comments', exact: true }).click()
    const comments = page.getByRole('tabpanel', { name: 'Comments', exact: true })
    await comments.getByLabel('New comment').fill('Confirm the studio name before sharing.')
    await comments.getByRole('button', { name: 'Comment on selection', exact: true }).click()
    const thread = comments.getByRole('article').first()
    await thread.getByLabel('Reply', { exact: true }).fill('Confirmed for this proposal.')
    await thread.getByRole('button', { name: 'Add reply', exact: true }).click()
    await thread.getByRole('button', { name: 'Resolve', exact: true }).click()
    await page.getByRole('tab', { name: 'Comments', exact: true }).focus()
    await page.screenshot({ path: `${output}/comments-${viewport.width}.png` })
    await thread.getByRole('button', { name: 'Show quoted text', exact: true }).click()
    await page.keyboard.press('Backspace')
    await expect(thread).toContainText('Detached')
    await page.getByRole('tab', { name: 'Comments', exact: true }).focus()
    await page.screenshot({ path: `${output}/detached-${viewport.width}.png` })
    await page.getByRole('button', { name: 'Save changes', exact: true }).click()
    await expect(page.getByTestId('save-status')).toHaveText('Saved')
    await page.getByRole('tab', { name: 'History', exact: true }).click()
    await page.locator('[data-revision-id]').last().click()
    await expect(page.getByRole('region', { name: 'Revision preview' })).toBeVisible()
    await page.mouse.move(4, 4)
    await page.screenshot({ path: `${output}/history-${viewport.width}.png` })
    const geometry = await page.evaluate(() => {
      const names = ['app-shell', 'outline', 'right-panel', 'workspace', 'paper', 'text-column']
      return Object.fromEntries(names.map(name => { const el = document.querySelector(`[data-testid="${name}"]`)!; const { x, y, width, height } = el.getBoundingClientRect(); return [name, { x, y, width, height, overflow: el.scrollWidth > el.clientWidth }] }))
    })
    expect(geometry['outline'].width).toBe(246)
    expect(geometry['right-panel'].width).toBe(300)
    expect(geometry['paper'].width).toBeLessThanOrEqual(816)
    expect(geometry['text-column'].width).toBeLessThanOrEqual(550)
    expect(geometry['app-shell'].width).toBe(Math.min(1440, viewport.width - 32))
    expect(geometry['app-shell'].height).toBe(Math.min(860, viewport.height - 118))
    for (const [name, value] of Object.entries(geometry)) expect(value.overflow, `${name}: ${JSON.stringify(value)}`).toBe(false)
    const preview = page.getByLabel('Preview document', { exact: true })
    await preview.evaluate(el => { el.scrollTop = el.scrollHeight })
    expect(await preview.evaluate(el => el.scrollTop)).toBeGreaterThan(0)
    await page.getByRole('button', { name: 'Close document tools', exact: true }).click()
    await page.getByRole('button', { name: 'Dismiss editing banner', exact: true }).click()
    await page.mouse.move(4, 4)
    await page.screenshot({ path: `${output}/closed-controls-${viewport.width}.png` })
    expect(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth || scrollY !== 0)).toBe(false)
    expect(errors).toEqual([])
    await writeFile(`${output}/panels-geometry-${viewport.width}.json`, JSON.stringify({ viewport, geometry, errors }, null, 2))
  })
}
