import { test, expect } from '@playwright/test'
import { reloadEditor, openEditor, selectText, stored, documentJSON } from './editor-helpers'

test.beforeEach(async ({ page }) => { await page.setViewportSize({ width: 1640, height: 1060 }) })

test('document and selected comments persist, anchors map and detach; replies resolve and reopen', async ({ page }) => {
  await openEditor(page)
  await page.getByRole('tab', { name: 'Comments', exact: true }).click()
  const panel = page.getByRole('tabpanel', { name: 'Comments', exact: true })
  await expect(panel.getByRole('button', { name: 'Comment on selection', exact: true })).toBeDisabled()
  await panel.getByLabel('New comment').fill('Document review')
  await panel.getByRole('button', { name: 'Add document comment', exact: true }).click()
  await selectText(page, 'Acme Studio')
  await panel.getByLabel('New comment').fill('Check studio name')
  await panel.getByRole('button', { name: 'Comment on selection', exact: true }).click()
  const thread = panel.getByRole('article', { name: 'Comment: Check studio name', exact: true })
  await thread.getByLabel('Reply', { exact: true }).fill('Confirmed with the team')
  await thread.getByRole('button', { name: 'Add reply', exact: true }).click()
  await thread.getByRole('button', { name: 'Resolve', exact: true }).click()
  await expect(thread.getByText('Resolved', { exact: true })).toBeVisible()
  await page.evaluate(() => { const e = window.__phase2Test!.editor!; e.view.dispatch(e.state.tr.insertText('Intro ', 1)) })
  await thread.getByRole('button', { name: 'Show quoted text', exact: true }).click()
  expect(await page.evaluate(() => { const e = window.__phase2Test!.editor!; return e.state.doc.textBetween(e.state.selection.from, e.state.selection.to) })).toBe('Acme Studio')
  await page.keyboard.press('Backspace')
  await expect(thread).toContainText('Detached — quoted text was removed.')
  await expect(thread.locator('blockquote')).toHaveText('Acme Studio')
  await page.keyboard.press('Meta+s')
  await expect(page.getByTestId('save-status')).toHaveText('Saved')
  await reloadEditor(page)
  await page.getByRole('tab', { name: 'Comments', exact: true }).click()
  await expect(panel.getByText('Document review', { exact: true })).toBeVisible()
  await expect(thread).toContainText('Confirmed with the team')
  await expect(thread).toContainText('Detached')
  await thread.getByRole('button', { name: 'Reopen', exact: true }).click()
  await expect(thread.getByText('Open', { exact: true })).toBeVisible()
  await page.keyboard.press('Meta+s')
  await expect(page.getByTestId('save-status')).toHaveText('Saved')
  expect((await stored(page)).comments[1].resolved).toBe(false)
})

test('preview is non-mutating; restoration preserves unsaved current document and revision comments', async ({ page }) => {
  await openEditor(page)
  await page.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect(page.getByTestId('save-status')).toHaveText('Saved')
  await page.getByRole('tab', { name: 'Comments', exact: true }).click()
  await page.getByLabel('New comment').fill('Current comment')
  await page.getByRole('button', { name: 'Add document comment', exact: true }).click()
  await selectText(page, 'Dear Alex,'); await page.keyboard.type('Current unsaved version')
  const current = await documentJSON(page)
  await page.getByRole('tab', { name: 'History', exact: true }).click()
  await page.locator('[data-revision-id]').last().click()
  await expect(page.getByRole('region', { name: 'Revision preview' })).toContainText('Dear Alex,')
  expect(await documentJSON(page)).toEqual(current)
  await page.getByRole('button', { name: 'Restore revision', exact: true }).click()
  await expect(page.getByTestId('document-editor')).toContainText('Dear Alex,')
  await expect(page.getByText('Revision restored.', { exact: false })).toBeVisible()
  await expect(page.getByRole('tab', { name: 'History', exact: true })).toBeFocused()
  await page.keyboard.press('Meta+s')
  await expect(page.getByTestId('save-status')).toHaveText('Saved')
  const data = await stored(page)
  expect(data.revisions.some((item: { document: unknown; comments: unknown[] }) => JSON.stringify(item.document) === JSON.stringify(current) && item.comments.length === 1)).toBe(true)
  expect(data.comments).toEqual([])
  await reloadEditor(page)
  await expect(page.getByTestId('document-editor')).toContainText('Dear Alex,')
})

test('failed pre-restore save is visible and leaves editor and preview intact; retry is explicit', async ({ page }) => {
  await openEditor(page)
  await expect(page.getByTestId('save-status')).toHaveText('Saved')
  await selectText(page, 'Dear Alex,'); await page.keyboard.type('Must preserve this version')
  const current = await documentJSON(page)
  await page.evaluate(() => { Storage.prototype.setItem = () => { throw Error('quota') } })
  await page.getByRole('tab', { name: 'History', exact: true }).click()
  await page.locator('[data-revision-id]').last().click()
  await page.getByRole('button', { name: 'Restore revision', exact: true }).click()
  await expect(page.getByRole('tabpanel', { name: 'History', exact: true }).getByRole('alert')).toContainText('Restoration stopped')
  expect(await documentJSON(page)).toEqual(current)
  await page.evaluate(() => { const iframe = document.createElement('iframe'); document.body.appendChild(iframe); Storage.prototype.setItem = (iframe.contentWindow as Window & typeof globalThis).Storage.prototype.setItem; iframe.remove() })
  await page.getByRole('button', { name: 'Restore revision', exact: true }).click()
  await expect(page.getByTestId('document-editor')).toContainText('Dear Alex,')
  expect((await stored(page)).revisions.some((item: { document: unknown }) => JSON.stringify(item.document) === JSON.stringify(current))).toBe(true)
})

test('tabs retain editor identity, workspace scroll, selection and Explain results; hidden loading is cancelled', async ({ page }) => {
  await openEditor(page)
  const editorHandle = await page.getByTestId('document-editor').elementHandle()
  await selectText(page, 'Acme Studio')
  await page.getByRole('button', { name: 'Ask AI', exact: true }).click()
  await page.getByTestId('explain-menu').getByRole('button', { name: /^Summary/ }).click()
  await expect(page.getByTestId('explain-result')).toBeVisible()
  const result = await page.getByTestId('explain-result').innerText()
  await page.getByTestId('workspace').evaluate(el => { el.scrollTop = 270 })
  const scroll = await page.getByTestId('workspace').evaluate(el => el.scrollTop)
  const before = await documentJSON(page)
  await page.getByRole('tab', { name: 'Comments', exact: true }).click()
  await page.getByLabel('New comment').fill('Draft stays here')
  await page.getByRole('tab', { name: 'History', exact: true }).click()
  await page.getByRole('tab', { name: 'Comments', exact: true }).click()
  await expect(page.getByLabel('New comment')).toHaveValue('Draft stays here')
  await page.getByRole('tab', { name: 'Explain', exact: true }).click()
  await expect(page.getByTestId('explain-result')).toHaveText(result)
  expect(await page.getByTestId('workspace').evaluate(el => el.scrollTop)).toBe(scroll)
  expect(await editorHandle!.evaluate(el => el === document.querySelector('[data-testid="document-editor"]'))).toBe(true)
  expect(await documentJSON(page)).toEqual(before)
  await page.getByRole('button', { name: 'Back', exact: true }).click()
  await page.getByTestId('explain-menu').getByRole('button', { name: /^Rewrite Make/ }).click()
  await page.getByRole('tab', { name: 'History', exact: true }).click()
  await page.getByRole('tab', { name: 'Explain', exact: true }).click()
  await expect(page.getByText('Response cancelled.', { exact: true })).toBeVisible()
  await page.waitForTimeout(700)
  await expect(page.getByTestId('explain-result')).toHaveCount(0)
})

test('tabs support arrows, Home/End and focus; close controls restore focus and orb mode behavior', async ({ page }) => {
  await openEditor(page)
  const explain = page.getByRole('tab', { name: 'Explain', exact: true })
  await explain.focus(); await page.keyboard.press('ArrowRight')
  await expect(page.getByRole('tab', { name: 'Comments', exact: true })).toBeFocused()
  await expect(page.getByRole('tab', { name: 'Comments', exact: true })).toHaveAttribute('aria-selected', 'true')
  await page.keyboard.press('End')
  await expect(page.getByRole('tab', { name: 'History', exact: true })).toBeFocused()
  await page.keyboard.press('Home'); await expect(explain).toBeFocused()
  await expect(explain).toHaveCSS('outline-width', '2px')
  await page.getByRole('button', { name: 'Dismiss editing banner', exact: true }).click()
  await expect(page.getByTestId('editing-banner')).toBeHidden()
  await expect(page.getByTestId('document-editor')).toBeFocused()
  await page.getByRole('button', { name: 'Close document tools', exact: true }).click()
  const orb = page.getByRole('button', { name: 'Explain mode', exact: true })
  await expect(orb).toBeFocused()
  await expect(page.getByTestId('right-panel')).toBeHidden()
  await orb.click()
  await expect(explain).toHaveAttribute('aria-selected', 'true')
  await expect(orb).toHaveAttribute('aria-pressed', 'true')
  await expect(page.locator('[data-clause-marker]')).toHaveCount(3)
  await page.getByRole('button', { name: 'Close document tools', exact: true }).click()
  await orb.click(); await expect(orb).toHaveAttribute('aria-pressed', 'true')
  await orb.click(); await expect(orb).toHaveAttribute('aria-pressed', 'false')
  await expect(page.locator('[data-clause-marker]')).toHaveCount(0)
})

test('reduced motion disables transitions and saving animation; normal controls use 150 ms ease-out', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  await openEditor(page, 120000)
  const tab = page.getByRole('tab', { name: 'Comments', exact: true })
  await expect(tab).toHaveCSS('transition-duration', '0.15s, 0.15s, 0.15s')
  await expect(tab).toHaveCSS('transition-timing-function', 'ease-out, ease-out, ease-out')
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect(page.getByTestId('saving-indicator')).toHaveAttribute('data-reduced-motion', 'true')
  await expect(tab).toHaveCSS('transition-duration', '0s')
  const before = await page.getByTestId('saving-indicator').innerHTML()
  await page.waitForTimeout(200)
  expect(await page.getByTestId('saving-indicator').innerHTML()).toBe(before)
})

test('comment save failure keeps draft data for retry and reload', async ({ page }) => {
  await openEditor(page)
  await expect(page.getByTestId('save-status')).toHaveText('Saved')
  await page.evaluate(() => { Storage.prototype.setItem = () => { throw Error('quota') } })
  await page.getByRole('tab', { name: 'Comments', exact: true }).click()
  await page.getByLabel('New comment').fill('Keep this comment through storage failure')
  await page.getByRole('button', { name: 'Add document comment', exact: true }).click()
  await page.keyboard.press('Meta+s')
  await expect(page.getByTestId('save-status')).toHaveText('Save failed')
  await expect(page.getByRole('article', { name: 'Comment: Keep this comment through storage failure', exact: true })).toBeVisible()
  await page.evaluate(() => { const iframe = document.createElement('iframe'); document.body.appendChild(iframe); Storage.prototype.setItem = (iframe.contentWindow as Window & typeof globalThis).Storage.prototype.setItem; iframe.remove() })
  await page.getByRole('button', { name: 'Retry save', exact: true }).first().click()
  await expect(page.getByTestId('save-status')).toHaveText('Saved')
  await reloadEditor(page)
  await page.getByRole('tab', { name: 'Comments', exact: true }).click()
  await expect(page.getByText('Keep this comment through storage failure', { exact: true })).toBeVisible()
})

test('source changes while Explain is hidden still disable a stale rewrite', async ({ page }) => {
  await openEditor(page)
  await selectText(page, 'Acme Studio')
  await page.getByRole('button', { name: 'Ask AI', exact: true }).click()
  await page.getByTestId('explain-menu').getByRole('button', { name: /^Rewrite Make/ }).click()
  await expect(page.getByRole('button', { name: 'Apply', exact: true })).toBeEnabled()
  await page.getByRole('tab', { name: 'Comments', exact: true }).click()
  await page.evaluate(() => { const e = window.__phase2Test!.editor!; e.view.dispatch(e.state.tr.insertText('Changed ', e.state.selection.from)) })
  const before = await documentJSON(page)
  await page.getByRole('tab', { name: 'Explain', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Apply', exact: true })).toBeDisabled()
  await expect(page.getByTestId('explain-menu')).toContainText('The selected text changed.')
  expect(await documentJSON(page)).toEqual(before)
})
